repos:
  # Basic file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        description: Trim trailing whitespace
      - id: end-of-file-fixer
        description: Ensure files end with a newline
      - id: check-yaml
        description: Check YAML syntax
      - id: check-added-large-files
        description: Check for large files

  # Import sorting
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        description: Sort Python imports
        args: [--profile, black, --line-length=88]

  # Code formatting
  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        description: Format Python code with Black
        language_version: python3
        args: [--line-length=88]

  # Linting for unused imports and variables
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        description: Lint Python code with Flake8
        args:
          - --max-line-length=88
          - --extend-ignore=E203,W503,E501
          - --select=E,W,F
